export const COLUMN_NAME_MAP = {
  'sicilno': 'Sicil No',
  'sicilid':'Sicil ID',
  'ıd':'ID',
  'ı d':"ID",
  'id':"ID",
  'ısim':"İsim",
  'isim':"İsim",
  'yas':"Yaş",
  'ad': 'Ad',
  'adi':' Adı',
  'yon':'Yön',
  'yonu':'Yönü',
  'soyad': 'Soyad',
  'personeldurum': 'Personel Durumu',
  'firma': 'Firma',
  'bolum': 'Bölüm',
  'gorev': 'Görev',
  'pozisyon': 'Pozisyon',
  'direktorluk': 'Direktörlük',
  'tariharalik':'Tarih Aralığı',
  'altfirma': 'Alt Firma',
  'yaka': 'Yaka',
  'yonetici': 'Yönetici',
  'giristarih': 'Giriş Tarihi',
  'cikistarih': 'Çıkış Tarihi',
  'ceptelefon': 'Cep Telefonu',
  'okuyucuadi':"Okuyucu Adı",
  'okuyucuyonu':"Okuyucu Yönü",
  'tkidem':"Toplam Kıdem",
  'mesaitarih':'Mesai Tarih',
  'email': 'E-Posta',
  'okod1': 'Özel Kod 1',
  'okod2': 'Özel Kod 2',
  'okod3': 'Özel Kod 3',
}

