import useReportStore from "../store/useReportStore";
import * as Layout from "../constants/layoutConstants.js";

function buildChart(item) {
  const dataItem = useReportStore
    .getState()
    .reportItems.find((ri) => ri.id === item.dataSourceId);
  const jsonKeys = dataItem ? dataItem.jsonKeys : [];

  return {
    Chart: {
      "@_Name": "Chart1",
      Left: "0pt",
      Top: `${Layout.PAGE_HEIGHT}pt`,
      Height: "216pt",
      Width: "288pt",
      Style: {
        BackgroundColor: "White",
        FontFamily: "Segoe UI",
        FontSize: "8pt",
        BackgroundGradientEndColor: "White",
        TextAlign: "Center",
        Color: "Gray",
        ShadowColor: "Transparent",
        Border: {
          Color: "#d3d3d3",
          Style: "Solid",
        },
      },
      DataSetName: `DataSet_${dataItem.id}`,
      ChartSeriesHierarchy: {
        ChartMembers: {
          ChartMember: jsonKeys.map((i) => {
            return {
              Label: i,
            };
          }),
        },
      },
      ChartCategoryHierarchy: {
        ChartMembers: [
          {
            ChartMember: {
              Group: {
                "@_Name": "Chart_Group1",
              },
              Label: null,
            },
          },
        ],
      },
      ChartData: {
        ChartSeriesCollection: {
          ChartSeries: jsonKeys.map((key) => {
            return {
              "@_Name": `${key}`,
              ChartDataPoints: {
                ChartDataPoint: {
                  ChartDataPointValues: {
                    Y: `=Sum(Fields!${key}.Value)`,
                  },
                  ChartDataLabel: {
                    Style: {
                      BackgroundGradientEndColor: "White",
                      Color: "Black",
                      ShadowColor: "Transparent",
                      Border: {
                        Color: "LightGrey",
                        Style: "None",
                      },
                    },
                    UseValueAsLabel: "false",
                    Label: "#PERCENT",
                    Visible: "false",
                    Position: "Auto",
                  },
                  Style: {
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "Transparent",
                      Style: "None",
                    },
                  },
                  ChartMarker: {
                    Size: "6pt",
                    Style: {
                      FontFamily: "Segoe UI",
                      FontSize: "8pt",
                      BackgroundGradientEndColor: "White",
                      ShadowColor: "Transparent",
                      Border: {
                        Color: "Transparent",
                        Style: "Solid",
                      },
                    },
                  },
                },
              },
              Type: "Shape",
              Style: {
                FontFamily: "Segoe UI",
                FontSize: "8pt",
                BackgroundGradientEndColor: "White",
                Color: "Gray",
                ShadowColor: "Transparent",
                Border: {
                  Color: "LightGrey",
                  Style: "Solid",
                },
              },
              ChartMarker: {
                Size: "6pt",
                Style: {
                  FontFamily: "Segoe UI",
                  FontSize: "8pt",
                  BackgroundGradientEndColor: "White",
                  ShadowColor: "Transparent",
                  Border: {
                    Color: "Transparent",
                    Style: "Solid",
                  },
                },
              },
              ValueAxisName: "Primary",
              CategoryAxisName: "Primary",
            };
          }),
        },
      },
      ChartAreas: {
        ChartArea: {
          "@_Name": "Default",
          ChartCategoryAxes: {
            ChartAxis: [
              {
                "@_Name": "Primary",
                Visible: "Auto",
                Style: {
                  BackgroundColor: "White",
                  FontFamily: "Segoe UI",
                  FontSize: "8pt",
                  BackgroundGradientEndColor: "White",
                  TextAlign: "Center",
                  Color: "Black",
                  ShadowColor: "Transparent",
                  Border: {
                    Color: "#808080",
                    Style: "Solid",
                  },
                },
                ChartAxisTitle: {
                  Caption: null,
                  Position: "Center",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Black",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#d3d3d3",
                      Style: "Solid",
                    },
                  },
                },
                Interval: 0,
                ChartMajorGridLines: {
                  Enabled: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#dcdcdc",
                      Style: "Solid",
                    },
                  },
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMinorGridLines: {
                  Enabled: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#dcdcdc",
                      Style: "Dotted",
                    },
                  },
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMajorTickMarks: {
                  Enabled: "false",
                  Type: "Outside",
                  Style: {
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Width: "0.75000pt",
                      Color: "Gray",
                      Style: "Solid",
                    },
                  },
                  Length: 1.5,
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMinorTickMarks: {
                  Enabled: "false",
                  Type: "Outside",
                  Style: {
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Width: "0.75000pt",
                      Color: "Gray",
                      Style: "Solid",
                    },
                  },
                  Length: 1,
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                Location: "Default",
                InterlacedColor: "Transparent",
                LabelsAutoFitDisabled: "True",
                ChartAxisScaleBreak: {
                  Enabled: "false",
                  BreakLineType: "Ragged",
                  CollapsibleSpaceThreshold: 25,
                  MaxNumberOfBreaks: 2,
                  Spacing: 0,
                  IncludeZero: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#d3d3d3",
                      Style: "Solid",
                    },
                  },
                },
              },
              {
                "@_Name": "Secondary",
                Visible: "Auto",
                Style: {
                  BackgroundColor: "White",
                  FontFamily: "Segoe UI",
                  FontSize: "8pt",
                  BackgroundGradientEndColor: "White",
                  TextAlign: "Center",
                  Color: "Black",
                  ShadowColor: "Transparent",
                  Border: {
                    Color: "#808080",
                    Style: "Solid",
                  },
                },
                ChartAxisTitle: {
                  Caption: null,
                  Position: "Center",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Black",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#d3d3d3",
                      Style: "Solid",
                    },
                  },
                },
                Interval: 0,
                ChartMajorGridLines: {
                  Enabled: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#dcdcdc",
                      Style: "Solid",
                    },
                  },
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMinorGridLines: {
                  Enabled: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#dcdcdc",
                      Style: "Dotted",
                    },
                  },
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMajorTickMarks: {
                  Enabled: "false",
                  Type: "Outside",
                  Style: {
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Width: "0.75000pt",
                      Color: "Gray",
                      Style: "Solid",
                    },
                  },
                  Length: 1.5,
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMinorTickMarks: {
                  Enabled: "false",
                  Type: "Outside",
                  Style: {
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Width: "0.75000pt",
                      Color: "Gray",
                      Style: "Solid",
                    },
                  },
                  Length: 1,
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                Location: "Opposite",
                InterlacedColor: "Transparent",
                LabelsAutoFitDisabled: "True",
                ChartAxisScaleBreak: {
                  Enabled: "false",
                  BreakLineType: "Ragged",
                  CollapsibleSpaceThreshold: 25,
                  MaxNumberOfBreaks: 2,
                  Spacing: 0,
                  IncludeZero: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#d3d3d3",
                      Style: "Solid",
                    },
                  },
                },
              },
            ],
          },
          ChartValueAxes: {
            ChartAxis: [
              {
                "@_Name": "Primary",
                Visible: "Auto",
                Style: {
                  BackgroundColor: "White",
                  FontFamily: "Segoe UI",
                  FontSize: "8pt",
                  BackgroundGradientEndColor: "White",
                  TextAlign: "Center",
                  Color: "Black",
                  ShadowColor: "Transparent",
                  Border: {
                    Color: "#808080",
                    Style: "Solid",
                  },
                },
                ChartAxisTitle: {
                  Caption: null,
                  Position: "Center",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Black",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#d3d3d3",
                      Style: "Solid",
                    },
                  },
                },
                Interval: 0,
                ChartMajorGridLines: {
                  Enabled: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#dcdcdc",
                      Style: "Solid",
                    },
                  },
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMinorGridLines: {
                  Enabled: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#dcdcdc",
                      Style: "Dotted",
                    },
                  },
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMajorTickMarks: {
                  Enabled: "false",
                  Type: "Outside",
                  Style: {
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Width: "0.75000pt",
                      Color: "Gray",
                      Style: "Solid",
                    },
                  },
                  Length: 1.5,
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMinorTickMarks: {
                  Enabled: "false",
                  Type: "Outside",
                  Style: {
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Width: "0.75000pt",
                      Color: "Gray",
                      Style: "Solid",
                    },
                  },
                  Length: 1,
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                Location: "Default",
                InterlacedColor: "Transparent",
                LabelsAutoFitDisabled: "True",
                ChartAxisScaleBreak: {
                  Enabled: "false",
                  BreakLineType: "Ragged",
                  CollapsibleSpaceThreshold: 25,
                  MaxNumberOfBreaks: 2,
                  Spacing: 0,
                  IncludeZero: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#d3d3d3",
                      Style: "Solid",
                    },
                  },
                },
              },
              {
                "@_Name": "Secondary",
                Visible: "Auto",
                Style: {
                  BackgroundColor: "White",
                  FontFamily: "Segoe UI",
                  FontSize: "8pt",
                  BackgroundGradientEndColor: "White",
                  TextAlign: "Center",
                  Color: "Black",
                  ShadowColor: "Transparent",
                  Border: {
                    Color: "#808080",
                    Style: "Solid",
                  },
                },
                ChartAxisTitle: {
                  Caption: null,
                  Position: "Center",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Black",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#d3d3d3",
                      Style: "Solid",
                    },
                  },
                },
                Interval: 0,
                ChartMajorGridLines: {
                  Enabled: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#dcdcdc",
                      Style: "Solid",
                    },
                  },
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMinorGridLines: {
                  Enabled: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#dcdcdc",
                      Style: "Dotted",
                    },
                  },
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMajorTickMarks: {
                  Enabled: "false",
                  Type: "Outside",
                  Style: {
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Width: "0.75000pt",
                      Color: "Gray",
                      Style: "Solid",
                    },
                  },
                  Length: 1.5,
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                ChartMinorTickMarks: {
                  Enabled: "false",
                  Type: "Outside",
                  Style: {
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Width: "0.75000pt",
                      Color: "Gray",
                      Style: "Solid",
                    },
                  },
                  Length: 1,
                  IntervalType: "Default",
                  IntervalOffsetType: "Default",
                },
                Location: "Opposite",
                InterlacedColor: "Transparent",
                LabelsAutoFitDisabled: "True",
                ChartAxisScaleBreak: {
                  Enabled: "false",
                  BreakLineType: "Ragged",
                  CollapsibleSpaceThreshold: 25,
                  MaxNumberOfBreaks: 2,
                  Spacing: 0,
                  IncludeZero: "Auto",
                  Style: {
                    BackgroundColor: "White",
                    FontFamily: "Segoe UI",
                    FontSize: "8pt",
                    BackgroundGradientEndColor: "White",
                    TextAlign: "Center",
                    Color: "Gray",
                    ShadowColor: "Transparent",
                    Border: {
                      Color: "#d3d3d3",
                      Style: "Solid",
                    },
                  },
                },
              },
            ],
          },
          Style: {
            BackgroundColor: "White",
            FontFamily: "Segoe UI",
            FontSize: "8pt",
            BackgroundGradientEndColor: "White",
            TextAlign: "Center",
            Color: "Gray",
            ShadowColor: "Transparent",
            Border: {
              Color: "#d3d3d3",
              Style: "None",
            },
          },
        },
      },
      ChartLegends: {
        ChartLegend: {
          "@_Name": "Default",
          Hidden: "false",
          Style: {
            BackgroundColor: "White",
            FontFamily: "Segoe UI",
            FontSize: "8pt",
            BackgroundGradientEndColor: "White",
            TextAlign: "Center",
            Color: "Black",
            ShadowColor: "Transparent",
            Border: {
              Color: "#d3d3d3",
              Style: "None",
            },
          },
          Position: "BottomCenter",
          ChartLegendTitle: {
            Caption: null,
            TitleSeparator: "None",
            Style: {
              FontFamily: "Segoe UI",
              FontSize: "8pt",
              FontWeight: "Bold",
              BackgroundGradientEndColor: "White",
              TextAlign: "Center",
              Color: "Gray",
              ShadowColor: "Transparent",
              Border: {
                Color: "LightGrey",
                Style: "None",
              },
            },
          },
          HeaderSeparator: "None",
          HeaderSeparatorColor: "Black",
          ColumnSeparator: "None",
          ColumnSeparatorColor: "Black",
          ColumnSpacing: 0,
          InterlacedRows: "false",
          InterlacedRowsColor: "Transparent",
          EquallySpacedItems: "false",
          Reversed: "Auto",
          TextWrapThreshold: 0,
        },
      },
      ChartTitles: {
        ChartTitle: {
          "@_Name": "Default",
          Caption: "Chart Title",
          Hidden: "false",
          Style: {
            FontFamily: "Segoe UI",
            FontSize: "10.5pt",
            FontWeight: "Bold",
            BackgroundGradientEndColor: "White",
            TextAlign: "General",
            VerticalAlign: "Top",
            Color: "Black",
            ShadowColor: "Transparent",
            Border: {
              Width: "0.75000pt",
              Color: "LightGrey",
              Style: "None",
            },
          },
          Position: "TopCenter",
          DockOffset: 0,
          TextOrientation: "Auto",
        },
      },

      Palette: "BrightPastel",
      ChartBorderSkin: {
        Style: {
          BackgroundColor: "White",
          FontFamily: "Segoe UI",
          FontSize: "8pt",
          BackgroundGradientEndColor: "White",
          TextAlign: "Center",
          Color: "White",
          ShadowColor: "Transparent",
          Border: {
            Color: "#d3d3d3",
            Style: "Solid",
          },
        },
      },
      ChartNoDataMessage: {
        "@_Name": "Default",
        Caption: null,
        Hidden: "false",
        Style: {
          BackgroundColor: "White",
          FontFamily: "Segoe UI",
          FontSize: "8pt",
          BackgroundGradientEndColor: "White",
          TextAlign: "Center",
          Color: "Gray",
          ShadowColor: "Transparent",
          Border: {
            Color: "#d3d3d3",
            Style: "Solid",
          },
        },
        Position: "TopCenter",
        DockOffset: 0,
        TextOrientation: "Auto",
      },
    },
  };
}

export default buildChart;
